services:
  pokeapp_database:
    image: postgres
    env_file:
      - .env
    container_name: poke_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  poke_app:
    image: poke_app
    entrypoint: ./entrypoint.sh
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - pokeapp_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@pokeapp_database:5432/app_db

volumes:
  pgdata: