services:
  pokeapp_database:
    image: postgres
    env_file:
      - .env
    container_name: poke_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  poke_app:
    image: poke_app
    container_name: poke_app
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - pokeapp_database
    entrypoint: [ "./entrypoint.sh" ]
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app

volumes:
  pgdata:
