"""remove dex_number in pokemon table

Revision ID: 0dc973aa5596
Revises: d0a819e51b92
Create Date: 2025-04-20 08:33:59.887532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc973aa5596'
down_revision: Union[str, None] = 'd0a819e51b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'dex_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('dex_number', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
