"""add created/updated at on trainers and pokemon table

Revision ID: 4397ddd624b7
Revises: 50abfd1a2c64
Create Date: 2025-04-29 18:05:33.659568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4397ddd624b7'
down_revision: Union[str, None] = '50abfd1a2c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('pokemon', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('trainers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('trainers', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainers', 'updated_at')
    op.drop_column('trainers', 'created_at')
    op.drop_column('pokemon', 'updated_at')
    op.drop_column('pokemon', 'created_at')
    # ### end Alembic commands ###
