"""create trainers table

Revision ID: 50abfd1a2c64
Revises: 96386ef3c36c
Create Date: 2025-04-29 12:46:20.718303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50abfd1a2c64'
down_revision: Union[str, None] = '96386ef3c36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_constraint('pokemon_trainer_id_fkey', 'pokemon', type_='foreignkey')
    op.create_foreign_key(None, 'pokemon', 'trainers', ['trainer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.create_foreign_key('pokemon_trainer_id_fkey', 'pokemon', 'users', ['trainer_id'], ['id'])
    op.drop_table('trainers')
    # ### end Alembic commands ###
