"""add dex_number in pokemon table

Revision ID: 6790cb4674f7
Revises: d446ebecf03e
Create Date: 2025-04-20 08:00:12.930251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6790cb4674f7'
down_revision: Union[str, None] = 'd446ebecf03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('dex_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'dex_number')
    # ### end Alembic commands ###
