"""create types table

Revision ID: 6a04018cef17
Revises: 597f78e2bdd6
Create Date: 2025-05-05 15:07:47.772473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a04018cef17'
down_revision: Union[str, None] = '597f78e2bdd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pokemon', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_type_pokemon', 'pokemon', 'types', ['type_id'], ['id'])
    op.drop_column('pokemon', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'type_id')
    op.drop_table('types')
    # ### end Alembic commands ###
