name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: copy repository archives
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install poetry
        run: pipx install poetry

      - name: Install dependencies
        run: pipx run poetry install

      - name: Run Linter
        run: pipx run poetry run task format


      - name: Run tests and generate coverage
        run: |
          pipx run poetry run coverage run -m pytest
          pipx run poetry run coverage xml

      - name: Run codacy-coverage-reporter
        env:
          CODACY_CONFIGURED: ${{ secrets.CODACY_PROJECT_TOKEN }}
        if: ${{ env.CODACY_CONFIGURED != ''}}
        uses: codacy/codacy-coverage-reporter-action@v1
        continue-on-error: true
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage.xml

      
